version: "3.8"

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=VMdb
    
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"